project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home 
    right:
      - about.qmd  
      - icon: github
        href: https://github.com/2DegreesInvesting/

format:
  html:
    theme: minty
    css: styles.css
    toc: true



